### ISSUE TITLE
weather app checklist

### ISSUE THREAD

**Issue by VihangaN** [VihangaN/hacktoberfest-2023#1]
- [x]  create map layout - @VihangaN 
- [x]  create country select dropdown - @SouMy16 
- [x]  detect user IP - @Dilshan97 
- [x]  create country flag on footer with user IP - @saura8668 
- [x]  integrate weather api ( [openweathermap](https://openweathermap.org/api) ) - @Dilshan97 
- [x]  integrate initial animated weather icons from [Bas Milius ](https://github.com/basmilius/weather-icons) - @VihangaN 
- [ ] Mobile responsiveness
- [ ]  Update animated weather icons ( refer to src/common/constant/weatherIcons.js )
- [ ]  Weather forcast - layout styling ( use grid view )
- [ ]  Weather forcast - add emoji icons ( moon phase etc )

**Comment by SouMy16** [comment]
> * [x]   create map layout - @VihangaN
> * [x ]   create country select dropdown - @SouMy16
> * [ ]   detect user IP
> * [ ]   create country flag on footer with user IP
> * [ ]   integrate weather api ( [openweathermap](https://openweathermap.org/api) )
> * [ ]   integrate animated weather icons from [Bas Milius ](https://github.com/basmilius/weather-icons)

**Comment by SouMy16** [comment]
> * [x]   create map layout - @VihangaN
> * [x]   create country select dropdown - @SouMy16
> * [ ]   detect user IP
> * [ ]   create country flag on footer with user IP
> * [ ]   integrate weather api ( [openweathermap](https://openweathermap.org/api) )
> * [ ]   integrate animated weather icons from [Bas Milius ](https://github.com/basmilius/weather-icons)

**Comment by saura8668** [comment]
Hey @VihangaN can u assignment me 3rd, 4th, 5th tasks from "Weather app checklist"?

**Comment by VihangaN** [comment]
> Hey @VihangaN can u assignment me 3rd, 4th, 5th tasks from "Weather app checklist"?
sure @saura8668

**Comment by VihangaN** [comment]
@saura8668 FYI :  @Dilshan97 has already implemented the user IP detection feature and the getting weather data feature

**Comment by saura8668** [comment]
@VihangaN I've implemented the "create country flag on footer with user IP". Please check

**Comment by VihangaN** [comment]
> @VihangaN I've implemented the "create country flag on footer with user IP". Please check

Thanks @saura8668

**Comment by saura8668** [comment]
Hey @VihangaN. Resolved the conflict and made a pull request. Please check.

**Comment by VihangaN** [comment]
> Hey @VihangaN. Resolved the conflict and made a pull request. Please check.

Thanks @saura8668 ! . Merged

**Comment by VihangaN** [comment]
**For new contributors** : you can contribute by updating weather icons. Refer to [src/common/constant/weatherIcons.js](https://github.com/VihangaN/hacktoberfest-2023/blob/a6c39e651d9a19272c16ce6f55c7a08b1fbca9b1/src/common/constant/weatherIcons.js) 🙂🚀

**Comment by Bawanthathilan** [comment]
@VihangaN  do you have any responsive design ?

**Comment by VihangaN** [comment]
> @VihangaN do you have any responsive design ?

@Bawanthathilan  No  , i don't have one . i'll create and update the README file

**Comment by Dilshan97** [comment]
@VihangaN I just implemented the weather forecast feature. #18 . need some ui styling for that.

**Comment by VihangaN** [comment]
> @VihangaN I just implemented the weather forecast feature. #18 . need some ui styling for that.

@Dilshan97  merged
